//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOC_SINH
    {
        public int ID_HS { get; set; }
        public Nullable<int> ID_LOP { get; set; }
        public string MA_HS { get; set; }
        public Nullable<int> ID_GV { get; set; }
        public string VANG_CO_PHEP { get; set; }
        public string VANG_KHONG_PHEP { get; set; }
        public Nullable<System.DateTime> NGAY_THEO_DOI { get; set; }
        public string BIEU_HIEN_CUA_HOC_SINH { get; set; }
        public string TEN_HOC_SINH { get; set; }
    }
}
