//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAO_VIEN
    {
        public int ID { get; set; }
        public string HO_TEN { get; set; }
        public string CHUC_VU { get; set; }
        public string TRINH_DO { get; set; }
        public string CHUYEN_MON { get; set; }
        public string DIA_CHI { get; set; }
        public string SO_DIEN_THOAI { get; set; }
    }
}
