//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_HOC
    {
        public int ID { get; set; }
        public string MA_LOP { get; set; }
        public string NAM_HOC { get; set; }
        public string TEN_LOP { get; set; }
    }
}
